### ISSUE TITLE
Displays for anonymous / guests

### ISSUE THREAD

**Issue by bcurran3** [dmzx/paypaldonation#12]
Donate button appears for anonymous/guests/unregistered users. This can cause confusion on which member made the donation and the ability to thank them personally. 

FEATURE REQUEST: Please add donation information to Admin or a new Donation log.

**Comment by Bitkiller25** [comment]
Is there meanwhile a possibility to hide the donate button, so that guest and unregistered user can´t see it? If so, how can I manage this?
Rgds - Bitkiller25

**Comment by Bitkiller25** [comment]
Oh, by the way, I wrote a German language file for this ext. Just in case, someone is interrested, please let me know.

Bitkiller25

**Comment by baua1310** [comment]
@Bitkiller25 can you send me a link to the German language file? Thanks.
