### ISSUE TITLE
Update "Donation stats" on donation

### ISSUE THREAD

**Issue by YoSev** [dmzx/paypaldonation#14]
Hello,

is the plugin supposed to update the "current donations" value if a donation has been done?
Mine doesn't and as i look through the code, i can't find a function that will update the current donated value, am i simply missing something?

I think it should be possible in the success function, right?
Awesome plugin!

Thank,
John

**Comment by dmzx** [comment]
No John this has to be done manual in this extension.
There is an extension available but in my VIP section on my forum that does it automatic.

**Comment by YoSev** [comment]
Ok, thanks,

I already implented it myself using a modified succes-callback url.
